# generated by datamodel-codegen:
#   filename:  questionaire.yml
#   timestamp: 2024-09-11T06:03:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Extra, Field


class Category(Enum):
    """
    The category of the commit.
    """

    Observability = 'Observability'
    Security = 'Security'
    Networking = 'Networking'
    Other = 'Other'


class CommitFeedback(BaseModel):
    """
    A schema to represent feedback on a commit.
    """

    class Config:
        extra = Extra.forbid

    is_good_feature: bool = Field(
        ..., description='Indicates if the commit represents a good feature.'
    )
    category: Category = Field(..., description='The category of the commit.')
    summary: Optional[str] = Field(
        None, description="A brief summary of the commit's feature."
    )
